In [27]:
gold_only_label_list_encoding_dict = {0: "OTHERS", 1: "PETITIONER", 2: "COURT", 3: "RESPONDENT", 4: "JUDGE", 5: "OTHER_PERSON", 6: "LAWYER", 7: "DATE", 8: "ORG", 9: "GPE", 10: "STATUTE", 11: "PROVISION", 12: "PRECEDENT", 13: "CASE_NUMBER", 14: "WITNESS"}

In [28]:
legalBART_mapping_to_gold_only_encoding_dict = {0: 0, 1: 1, 2: 1, 3: 2, 4: 2, 5: 3, 6: 3, 7: 5, 8: 5, 9: 5, 10: 5, 11: 6, 12: 6, 13: 7, 14: 7, 15: 9, 16: 9, 17: 10, 18: 10, 19: 11, 20: 11, 21: 11, 22: 11, 23: 12, 24: 12, 25: 13, 26: 13, 27: 14, 28: 14}

In [29]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Colab Notebooks/

import json
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/Colab Notebooks

In [30]:
legalBARTSamples_df_judgement = pd.read_csv('Data_Augmentation_for_Low_Resource_Indian_Legal_NER/ner_judgement.csv')
legalBARTSamples_df_preamble = pd.read_csv('Data_Augmentation_for_Low_Resource_Indian_Legal_NER/ner_preamble.csv')
legalBARTSamples = legalBARTSamples_df_judgement.append(legalBARTSamples_df_preamble, ignore_index=True)
legalBARTSamples['tokens'] = legalBARTSamples['tokens'].map(lambda x: eval(x))
legalBARTSamples['ner_tags'] = legalBARTSamples['ner_tags'].map(lambda x: eval(x))

<ipython-input-30-e81fc16a2363>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  legalBARTSamples = legalBARTSamples_df_judgement.append(legalBARTSamples_df_preamble, ignore_index=True)

In [31]:
legalBARTSamples

,tokens,ner_tags
0,"[On, specific, query, by, the, Bench, ,, it, w...","[0, 0, 0, 0, 7, 1, 7, 13, 11, 0, 0, 0, 0, 7, 0..."
1,"[According, to, the, Agya, ,, span, class, '',...","[0, 7, 7, 5, 7, 0, 3, 0, 0, 0, 0, 0, 0, 0, 13,..."
2,"[PW3, Vijay, Mishra, ,, Deputy, Manager, ,, HD...","[0, 13, 14, 7, 3, 0, 7, 0, 3, 7, 7, 7, 0, 0, 0..."
3,"[He, was, asked, to, come, and, carry, out, th...","[0, 11, 0, 7, 0, 7, 0, 0, 7, 1, 0, 0, 0, 0, 11..."
4,"[The, pillion, rider, ,, Satyanarayana, Murthy...","[7, 0, 0, 7, 5, 5, 11, 0, 0, 7, 7, 0, 7, 7, 0,..."
...,...,...
8389,"[The, Honble, Sri, Justice, Nooty, Ramamohana,...","[3, 0, 0, 3, 3, 4, 4, 0, 0, 0, 1, 0, 0, 0, 1, ..."
8390,"[Petitioner, :, Indira, Nehru, Gandhi, Respond...","[0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, ..."
8391,"[In, The, Court, Of, Sh, ., R.K, ., Sharma, ,,...","[0, 3, 3, 1, 0, 0, 3, 4, 1, 0, 0, 0, 3, 0, 0, ..."
8392,"[Petitioner, :, Bhagwant, Singh, Vs, ., Respon...","[0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, ..."
8393,"[In, The, Court, Of, Sh, ., M.K, ., Choudhary,...","[0, 3, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, ..."

In [32]:
def fix_encoding(row):
  for i, ner in enumerate(row['ner_tags']):
    row['ner_tags'][i] = legalBART_mapping_to_gold_only_encoding_dict[ner]
  return row['ner_tags']

In [33]:
legalBARTSamples['ner_tags'] = legalBARTSamples.apply(fix_encoding, axis=1)

In [34]:
legalBARTSamples

,tokens,ner_tags
0,"[On, specific, query, by, the, Bench, ,, it, w...","[0, 0, 0, 0, 5, 1, 5, 7, 6, 0, 0, 0, 0, 5, 0, ..."
1,"[According, to, the, Agya, ,, span, class, '',...","[0, 5, 5, 3, 5, 0, 2, 0, 0, 0, 0, 0, 0, 0, 7, ..."
2,"[PW3, Vijay, Mishra, ,, Deputy, Manager, ,, HD...","[0, 7, 7, 5, 2, 0, 5, 0, 2, 5, 5, 5, 0, 0, 0, ..."
3,"[He, was, asked, to, come, and, carry, out, th...","[0, 6, 0, 5, 0, 5, 0, 0, 5, 1, 0, 0, 0, 0, 6, ..."
4,"[The, pillion, rider, ,, Satyanarayana, Murthy...","[5, 0, 0, 5, 3, 3, 6, 0, 0, 5, 5, 0, 5, 5, 0, ..."
...,...,...
8389,"[The, Honble, Sri, Justice, Nooty, Ramamohana,...","[2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 1, 0, 0, 0, 1, ..."
8390,"[Petitioner, :, Indira, Nehru, Gandhi, Respond...","[0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, ..."
8391,"[In, The, Court, Of, Sh, ., R.K, ., Sharma, ,,...","[0, 2, 2, 1, 0, 0, 2, 2, 1, 0, 0, 0, 2, 0, 0, ..."
8392,"[Petitioner, :, Bhagwant, Singh, Vs, ., Respon...","[0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, ..."
8393,"[In, The, Court, Of, Sh, ., M.K, ., Choudhary,...","[0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, ..."

In [36]:
legalBARTSamples.to_csv('legal_BART_Samples.csv', encoding='utf-8', index=False)